services:
  mysql:
    image: mysql:8
    platform: linux/amd64
    environment:
      - MYSQL_DATABASE=bookworm
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pw
      - MYSQL_ROOT_PASSWORD=rootpw
    ports:
      - '3306:3306'