spring.application.name=bookworm
spring.datasource.url=jdbc:mysql://localhost:3306/bookworm
spring.datasource.username=user
spring.datasource.password=pw
spring.jpa.hibernate.ddl-auto=update
spring.docker.compose.lifecycle-management=start_only